---
  - name: Setup Galera cluster
    hosts: galera
    gather_facts: true
    tasks:
      - name: Update apt cache
        apt: update_cache=yes

      - name: Add Galera repository
        apt_repository:
          repo: deb http://ftp.osuosl.org/pub/mariadb/repo/10.0/ubuntu trusty main
          state: present
          filename: galera

      - name: Add GPG keys for Galera repository
        apt_key:
          keyserver: hkp://keyserver.ubuntu.com:80
          id: '0xF1656F24C74CD1D8'

      - name: Update apt cache
        apt: update_cache=yes

      - name: Install Galera packages
        apt:
          name: '{{ item }}'
          state: present
          allow_unauthenticated: yes
        with_items:
          - rsync
          - mariadb-galera-server

      - name: Create mew Galera cluster configuration
        template:
          src: '{{ playbook_dir }}/common/templates/galera.cnf.j2'
          dest: /etc/mysql/conf.d/galera.cnf
          owner: mysql
          mode: 0644

      - name: Stop MariaDB across the nodes
        service:
          name: mysql
          state: stopped

      - name: Ensure MariaDB is stopped
        wait_for:
          port: 3306
          state: stopped

      - name: Stop MariaDB on first node as a new Galera cluster
        service:
          name: mysql
          state: started
          arguments: '--wsrep-new-cluster'
        when: ansible_hostname == groups.galera.0

      - name: Start MariaDB on other cluster nodes
        service:
          name: mysql
          state: started
        when: ansible_hostname != groups.galera.0
