---
  - name: Identify lab hosts to build on
    hosts: lab
    become: true
    vars:
      rabbit_nodes:
        - node1_rabbit_mq_container
        - node2_rabbit_mq_container
        - node3_rabbit_mq_container
      galera_nodes:
        - node1_galera_container
        - node2_galera_container
        - node3_galera_container
    tasks:
      - name: Loading playbook configurations
        include_vars:
          file: 'lab_overrides.yml'

      - name: Install dependency packages for lxc
        apt: name={{ item }} state=present
        with_items:
          - lxc
          - lxc-dev
          - lxc-templates
 
      - name: Install LXC python bindings
        pip:
          name: lxc-python2

      - name: Determine if we need to create a Rabbit MQ cluster
        set_fact:
          rabbit_nodes: []
        when: install_rabbit_mq == False 

      - name: Determine if we need to create a Galera  cluster
        set_fact:
          galera_nodes: []
        when: install_galera == False 

      - name: Create LXC containers
        lxc_container:
          name: '{{ item }}'
          container_log: true
          template: ubuntu
          state: started
          template_options: --release trusty
          container_config:
            - "lxc.start.auto=1"
            - "lxc.start.delay=3"
          container_command: |
            while [[ ! $(ip a s eth0) =~ "inet " ]]
             do
              sleep 1
             done
            
            if [ ! -d /root/.ssh ]; then
             mkdir /root/.ssh
             chmod 0700 /root/.ssh
             echo "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}" | tee -a /root/.ssh/authorized_keys
            fi 
        with_items: 
          - '{{ rabbit_nodes }}'
          - '{{ galera_nodes }}'
        register: container_info
        when: ( galera_nodes|length > 0) or ( rabbit_nodes|length > 0)

      - name: Build in-memory inventory
        add_host:
          name: '{{ item.item }}'
          ansible_host: '{{ item.lxc_container.ips.0 }}'
          groups: all_containers
        with_items: '{{ container_info.results }}'

      - name: Create Rabbit MQ hosts group
        add_host:
          name: "{{ item }}"
          group: rabbit
        with_items: "{{ groups['all_containers'] }}"
        when: item is search("_rabbit_mq_container")
          
      - name: Create Galera hosts group
        add_host:
          name: "{{ item }}"
          group: galera
        with_items: "{{ groups['all_containers'] }}"
        when: item is search("_galera_container")
          
      - name: Write in-memory inventory to file
        template:
          src: '{{ playbook_dir }}/common/templates/ansible_inventory.j2'
          dest: '{{ playbook_dir}}/inventory/ansible_hosts'
          owner: root
          group: root
          mode: 0644
 
      - name: Update ansible inventory with host IP address
        lineinfile:
          regexp: '^{{ item.item }}'
          line: '{{ item.item }}  ansible_host={{ item.lxc_container.ips.0 }}'
          state: present
          dest: '{{ playbook_dir}}/inventory/ansible_hosts'
        with_items: "{{ container_info.results }}"

      - name: Add SSH fingerpring to ~/.ssh/known_hosts
        shell: ssh-keyscan -H '{{ item.lxc_container.ips.0 }}' >> ~/.ssh/known_hosts
        with_items: "{{ container_info.results }}"

      - name: Install python on each container
        shell: lxc-attach -n "{{ item }}" -- apt install -y python-minimal
        with_items: "{{ groups['all_containers'] }}"
